services:
  inventario-back:
    image: 'inventario-backend:latest'
    build:
      context: .
    container_name: inventario-back
    ports:
      - "8080:8080"
    depends_on:
      - inventario-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  inventario-db:
    image: 'postgres:17.4-alpine'
    container_name: inventario-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=inventario
      - POSTGRES_PASSWORD=qIFeYmFt8vkCToxHlbD2O7mh1Ht15YEQ
      - POSTGRES_DB=inventario
    volumes:
      - ./data:/var/lib/postgresql/data

  inventario-pgadmin:
    image: 'dpage/pgadmin4:9.3'
    container_name: inventario-pgadmin
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - inventario-db

  inventario-image-server:
    image: nginx:alpine
    container_name: inventario-image-server
    ports:
      - "8082:80"
    volumes:
      - ./images:/usr/share/nginx/html/images:ro